defaults:
        - override hydra/hydra_logging: none
        - override hydra/job_logging: custom
        - _self_

hydra:
  run:
    dir: ../hydra/${hydra.job.name}/${now:%Y-%B-%d_%H-%M-%S}

# run
codename: ut_ood
device: 'cuda'

# training
max_iter: 10000
bs: 128
lr: 1e-4
tf: false

# model
d_model: 256
num_heads: 4
num_layers: 6
label_pe: false
masked: false
copy_dec: false
alibi: false
copy_ut: false
regr_ut: false

# data
max_len: 5
max_nes: 2
step_generator: false
ops: 'asmif'
simplify: false
simplify_w_value: false
substitute: false
same_vocab: false